language: node_js

node_js: 8

services:
  - mongodb

cache:
  directories:
    - node_modules
      
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
    skip_cleanup: true